# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\yumsa\OneDrive\문서\그그그그거\BCB411A8273F6DC0522C3C68F3E3EF03062ED45A\PythonApplication3\testui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(763, 551)
        MainWindow.setMinimumSize(QtCore.QSize(243, 192))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_7.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.drop_shadow_frame = QtWidgets.QFrame(self.page)
        self.drop_shadow_frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(223, 207, 190, 255), stop: 1 rgba(248, 230, 211));\n"
"border-radius: 10px;")
        self.drop_shadow_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.drop_shadow_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.drop_shadow_frame.setObjectName("drop_shadow_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.drop_shadow_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.title_bar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.title_bar.setStyleSheet("background-color: none;")
        self.title_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_title = QtWidgets.QFrame(self.title_bar)
        self.frame_title.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed Light")
        font.setPointSize(14)
        self.frame_title.setFont(font)
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_title)
        self.verticalLayout_2.setContentsMargins(15, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_title = QtWidgets.QLabel(self.frame_title)
        font = QtGui.QFont()
        font.setFamily("모리스9")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(128, 102, 168);\n"
"font: 12pt \"모리스9\";")
        self.label_title.setObjectName("label_title")
        self.verticalLayout_2.addWidget(self.label_title)
        self.frame_6 = QtWidgets.QFrame(self.frame_title)
        self.frame_6.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.op_slide = QtWidgets.QSlider(self.frame_6)
        self.op_slide.setStyleSheet("color: rgb(128, 102, 168);")
        self.op_slide.setOrientation(QtCore.Qt.Horizontal)
        self.op_slide.setObjectName("op_slide")
        self.horizontalLayout_10.addWidget(self.op_slide)
        self.pin_button = QtWidgets.QPushButton(self.frame_6)
        self.pin_button.setMinimumSize(QtCore.QSize(20, 20))
        self.pin_button.setMaximumSize(QtCore.QSize(20, 20))
        self.pin_button.setStyleSheet("QPushButton {\n"
"    border-image: url(:/pin_png/UI_img/pin_black.png);\n"
"}\n"
"QPushButton:hover {\n"
"    border: none;\n"
"    border-radius: 8px;    \n"
"    background-color: rgba(255, 255, 255, 150);\n"
"}")
        self.pin_button.setText("")
        self.pin_button.setObjectName("pin_button")
        self.horizontalLayout_10.addWidget(self.pin_button)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_10)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.horizontalLayout.addWidget(self.frame_title)
        self.frame_btns = QtWidgets.QFrame(self.title_bar)
        self.frame_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName("frame_btns")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_btns)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_maximize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_maximize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_maximize.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_maximize.setStyleSheet("QPushButton {\n"
"}\n"
"QPushButton:hover {\n"
"    border: none;\n"
"    border-radius: 8px;    \n"
"    background-color: rgba(85, 255, 127, 150);\n"
"}")
        self.btn_maximize.setObjectName("btn_maximize")
        self.horizontalLayout_3.addWidget(self.btn_maximize)
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_minimize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_minimize.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_minimize.setStyleSheet("QPushButton {\n"
"    border-image: url(:/GO/UI_img/go_full_black.png);\n"
"}\n"
"QPushButton:hover {\n"
"    border: none;\n"
"    border-radius: 8px;    \n"
"    background-color: rgba(255, 170, 0, 150);\n"
"}")
        self.btn_minimize.setText("")
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_3.addWidget(self.btn_minimize)
        self.btn_close = QtWidgets.QPushButton(self.frame_btns)
        self.btn_close.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_close.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_close.setStyleSheet("QPushButton {\n"
"    border-image: url(:/GO/UI_img/go_close_black.png);\n"
"}\n"
"QPushButton:hover {\n"
"    border: none;\n"
"    border-radius: 8px;    \n"
"    background-color: rgba(255, 0, 0, 150);\n"
"}")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_3.addWidget(self.btn_close)
        self.horizontalLayout.addWidget(self.frame_btns)
        self.verticalLayout.addWidget(self.title_bar)
        self.content_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.content_bar.setStyleSheet("background-color: none;")
        self.content_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_bar.setObjectName("content_bar")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.content_bar)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWindow = QtWidgets.QStackedWidget(self.content_bar)
        self.stackedWindow.setStyleSheet("background-color: none;")
        self.stackedWindow.setObjectName("stackedWindow")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_home)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_content_home = QtWidgets.QFrame(self.page_home)
        self.frame_content_home.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_content_home.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content_home.setObjectName("frame_content_home")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_content_home)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_infos = QtWidgets.QFrame(self.frame_content_home)
        self.frame_infos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_infos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_infos.setObjectName("frame_infos")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_infos)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame = QtWidgets.QFrame(self.frame_infos)
        self.frame.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.start_btn = QtWidgets.QPushButton(self.frame)
        self.start_btn.setMinimumSize(QtCore.QSize(200, 80))
        self.start_btn.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.start_btn.setStyleSheet("QPushButton {\n"
"    border-radius: 40px;\n"
"    background-color: rgb(174, 230, 203)\n"
"}\n"
"QPushButton:hover {\n"
"    border-radius: 40px;\n"
"    background-color: rgb(174, 230, 203, 150);\n"
"}")
        self.start_btn.setObjectName("start_btn")
        self.verticalLayout_6.addWidget(self.start_btn)
        self.quit_btn = QtWidgets.QPushButton(self.frame)
        self.quit_btn.setMinimumSize(QtCore.QSize(200, 80))
        self.quit_btn.setStyleSheet("QPushButton {\n"
"    border-radius: 40px;\n"
"    background-color: rgb(205, 238, 243)\n"
"}\n"
"QPushButton:hover {\n"
"    border-radius: 40px;\n"
"    background-color: rgb(205, 238, 243, 150);\n"
"}")
        self.quit_btn.setObjectName("quit_btn")
        self.verticalLayout_6.addWidget(self.quit_btn)
        self.set_btn = QtWidgets.QPushButton(self.frame)
        self.set_btn.setMinimumSize(QtCore.QSize(200, 80))
        self.set_btn.setStyleSheet("QPushButton {\n"
"    border-radius: 40px;\n"
"    background-color: rgb(218, 241, 222)\n"
"}\n"
"QPushButton:hover {\n"
"    border-radius: 40px;\n"
"    background-color: rgb(218, 241, 222, 150)\n"
"}")
        self.set_btn.setObjectName("set_btn")
        self.verticalLayout_6.addWidget(self.set_btn)
        self.text_translate = QtWidgets.QTextEdit(self.frame)
        self.text_translate.setMaximumSize(QtCore.QSize(16777215, 30))
        self.text_translate.setObjectName("text_translate")
        self.verticalLayout_6.addWidget(self.text_translate)
        self.horizontalLayout_4.addWidget(self.frame)
        self.verticalLayout_9.addWidget(self.frame_infos)
        self.verticalLayout_5.addWidget(self.frame_content_home)
        self.stackedWindow.addWidget(self.page_home)
        self.page_credits = QtWidgets.QWidget()
        self.page_credits.setObjectName("page_credits")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page_credits)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.webvideo = QtWebEngineWidgets.QWebEngineView(self.page_credits)
        self.webvideo.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.webvideo.setUrl(QtCore.QUrl("about:blank"))
        self.webvideo.setObjectName("webvideo")
        self.horizontalLayout_5.addWidget(self.webvideo)
        self.stackedWindow.addWidget(self.page_credits)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(200, 160, 211, 81))
        self.label_3.setObjectName("label_3")
        self.stackedWindow.addWidget(self.page_2)
        self.verticalLayout_4.addWidget(self.stackedWindow)
        self.verticalLayout.addWidget(self.content_bar)
        self.credits_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.credits_bar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.credits_bar.setStyleSheet("background-color: none;")
        self.credits_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.credits_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.credits_bar.setObjectName("credits_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.credits_bar)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_label_credits = QtWidgets.QFrame(self.credits_bar)
        self.frame_label_credits.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_label_credits.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_credits.setObjectName("frame_label_credits")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_label_credits)
        self.verticalLayout_3.setContentsMargins(15, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_credits = QtWidgets.QLabel(self.frame_label_credits)
        font = QtGui.QFont()
        font.setFamily("모리스9")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("color: rgb(128, 102, 168);\n"
"font: 9pt \"모리스9\";")
        self.label_credits.setObjectName("label_credits")
        self.verticalLayout_3.addWidget(self.label_credits)
        self.horizontalLayout_2.addWidget(self.frame_label_credits)
        self.frame_grip = QtWidgets.QFrame(self.credits_bar)
        self.frame_grip.setMinimumSize(QtCore.QSize(30, 30))
        self.frame_grip.setMaximumSize(QtCore.QSize(30, 30))
        self.frame_grip.setStyleSheet("padding: 5px;")
        self.frame_grip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip.setObjectName("frame_grip")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_grip)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.return_btn = QtWidgets.QPushButton(self.frame_grip)
        self.return_btn.setStyleSheet("QPushButton {\n"
"    border-image: url(:/GO/UI_img/go_page_small.png);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 0, 0, 50);\n"
"}")
        self.return_btn.setText("")
        self.return_btn.setObjectName("return_btn")
        self.gridLayout.addWidget(self.return_btn, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_grip)
        self.verticalLayout.addWidget(self.credits_bar)
        self.horizontalLayout_7.addWidget(self.drop_shadow_frame)
        self.stackedWidget.addWidget(self.page)
        self.full_size = QtWidgets.QWidget()
        self.full_size.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(223, 207, 190, 255), stop: 1 rgba(248, 230, 211));\n"
"border-radius: 10px;")
        self.full_size.setObjectName("full_size")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.full_size)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_3 = QtWidgets.QFrame(self.full_size)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_3.setStyleSheet("background-color: none;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setMaximumSize(QtCore.QSize(10, 20))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.op_slide_2 = QtWidgets.QSlider(self.frame_4)
        self.op_slide_2.setOrientation(QtCore.Qt.Horizontal)
        self.op_slide_2.setObjectName("op_slide_2")
        self.horizontalLayout_8.addWidget(self.op_slide_2, 0, QtCore.Qt.AlignLeft)
        self.pin_button_2 = QtWidgets.QPushButton(self.frame_4)
        self.pin_button_2.setMaximumSize(QtCore.QSize(15, 15))
        self.pin_button_2.setStyleSheet("QPushButton {\n"
"    border-image: url(:/pin_png/UI_img/pin_black.png);\n"
"}\n"
"QPushButton:hover {\n"
"    border: none;\n"
"    border-radius: 4px;    \n"
"    background-color: rgba(255, 255, 255, 150);\n"
"}")
        self.pin_button_2.setText("")
        self.pin_button_2.setObjectName("pin_button_2")
        self.horizontalLayout_8.addWidget(self.pin_button_2)
        self.horizontalLayout_6.addWidget(self.frame_4, 0, QtCore.Qt.AlignRight)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setMaximumSize(QtCore.QSize(40, 20))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.full_size_quit_btn = QtWidgets.QPushButton(self.frame_5)
        self.full_size_quit_btn.setMinimumSize(QtCore.QSize(10, 10))
        self.full_size_quit_btn.setMaximumSize(QtCore.QSize(15, 15))
        self.full_size_quit_btn.setStyleSheet("QPushButton {\n"
"    border-image: url(:/GO/UI_img/go_small_size.png);\n"
"}\n"
"QPushButton:hover {\n"
"    border: none;\n"
"    border-radius: 4px;    \n"
"    background-color: rgba(255, 255, 255, 150);\n"
"}")
        self.full_size_quit_btn.setText("")
        self.full_size_quit_btn.setObjectName("full_size_quit_btn")
        self.horizontalLayout_12.addWidget(self.full_size_quit_btn)
        self.pushButton = QtWidgets.QPushButton(self.frame_5)
        self.pushButton.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border-image: url(:/GO/UI_img/go_close_black.png);\n"
"}\n"
"QPushButton:hover {\n"
"    border: none;\n"
"    border-radius: 4px;    \n"
"    background-color: rgba(255, 0, 0, 150);\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_12.addWidget(self.pushButton)
        self.horizontalLayout_6.addWidget(self.frame_5)
        self.verticalLayout_8.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.full_size)
        self.frame_2.setStyleSheet("background-color: none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(self.page_3)
        self.widget.setObjectName("widget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.webvideo_2 = QtWebEngineWidgets.QWebEngineView(self.widget)
        self.webvideo_2.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.webvideo_2.setUrl(QtCore.QUrl("about:blank"))
        self.webvideo_2.setObjectName("webvideo_2")
        self.horizontalLayout_9.addWidget(self.webvideo_2)
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 1)
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_4 = QtWidgets.QLabel(self.page_4)
        self.label_4.setGeometry(QtCore.QRect(210, 150, 261, 111))
        self.label_4.setObjectName("label_4")
        self.stackedWidget_2.addWidget(self.page_4)
        self.gridLayout_2.addWidget(self.stackedWidget_2, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.frame_2)
        self.stackedWidget.addWidget(self.full_size)
        self.verticalLayout_7.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWindow.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "수어 번역기"))
        self.op_slide.setToolTip(_translate("MainWindow", "<html><head/><body><p>투명도</p></body></html>"))
        self.btn_maximize.setToolTip(_translate("MainWindow", "Maximize"))
        self.btn_maximize.setText(_translate("MainWindow", "_"))
        self.btn_minimize.setToolTip(_translate("MainWindow", "Minimize"))
        self.btn_close.setToolTip(_translate("MainWindow", "Close"))
        self.start_btn.setText(_translate("MainWindow", "Traslate_start"))
        self.quit_btn.setText(_translate("MainWindow", "Quit"))
        self.set_btn.setText(_translate("MainWindow", "Setting"))
        self.text_translate.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "이곳에 동영상 재생을 넣어 주십시오"))
        self.label_credits.setText(_translate("MainWindow", "made by IF-O_range with pico"))
        self.label_4.setText(_translate("MainWindow", "이곳은 전체화면 동영상이 재생 될곳입니다."))
from PyQt5 import QtWebEngineWidgets
import pyui_resource_rc
